# Generated by Django 3.2.7 on 2021-09-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('stock_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('unit_price', models.FloatField()),
                ('customer_id', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
